id: dk.ehmi.eds.testscripts
canonical: http://medcomehmi.dk/ig/edstestscripts
name: EDSTestScripts
title: EDS Test Scripts
description: Testscripts for EHMI Delivery Service (EDS). Aka. EHMI Track n' Trace.
status: draft # draft | active | retired | unknown
version: 0.1.0
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2025+
releaseLabel: ci-build
jurisdiction: urn:iso:std:iso:3166#DK "Denmark"
publisher:
  name: MedCom
  url: https://medcom.dk
  email: ehmi@medcom.dk

dependencies:
  dk.ehmi.eds: dev
  dk.ehmi.eer: dev

menu:
  Home: index.html
  TouchStone Test Scripts: testscripts.html
  Test Examples - Test Protocol: testexamples.html # if relevant
  Artifacts: artifacts.html
  More:
    Table of Contents: toc.html
    Downloads: downloads.html
    Dependencies: dependencies.html

parameters:
  apply-version: false
  default-version: true
  apply-publisher: false
  default-publisher: true
  pin-canonicals: pin-multiples
  excludettl: true